INFO:werkzeug: * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:1000 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:1000 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:1234 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 18:34:35] "[33mGET / HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 18:34:35] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
ERROR:app:Exception on /list [GET]
Traceback (most recent call last):
  File "E:\! “–≈Õ»Õ√» !\! PYTHON SKYPRO !\lesson12_project_source_v3\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\! “–≈Õ»Õ√» !\! PYTHON SKYPRO !\lesson12_project_source_v3\venv\lib\site-packages\flask\app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "E:\! “–≈Õ»Õ√» !\! PYTHON SKYPRO !\lesson12_project_source_v3\venv\lib\site-packages\flask\app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "E:\! “–≈Õ»Õ√» !\! PYTHON SKYPRO !\lesson12_project_source_v3\venv\lib\site-packages\flask\app.py", line 1695, in make_response
    raise TypeError(
TypeError: The view function for 'page_tag' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 18:34:53] "[35m[1mGET /list HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:1234 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:1234 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:1234 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:1234 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:1234 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:1234 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:1234 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:1234 (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://127.0.0.1:1231 (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 223-099-058
INFO:werkzeug: * Detected change in 'C:\\Users\\ ÓÒÏÓÌ‡‚Ú\\Documents\\GitHub\\lesson12_project_source_v3\\app.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 223-099-058
INFO:werkzeug: * Running on http://127.0.0.1:4000 (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 223-099-058
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 18:42:39] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 18:42:39] "GET /static/style.css HTTP/1.1" 200 -
INFO:root:¬˚ÔÓÎÌˇ˛ ÔÓËÒÍ
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 18:42:46] "[35m[1mGET /search/?s=ÍÛ·‡ HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 18:42:46] "GET /search/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 18:42:46] "GET /search/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 18:42:46] "GET /search/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 18:42:46] "[36mGET /search/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://127.0.0.1:4000 (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 223-099-058
INFO:werkzeug: * Detected change in 'C:\\Users\\ ÓÒÏÓÌ‡‚Ú\\Documents\\GitHub\\lesson12_project_source_v3\\app.py', reloading
INFO:werkzeug: * Restarting with stat
INFO:werkzeug: * Running on http://127.0.0.1:4000 (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 18:45:59] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 18:46:00] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:root:¬˚ÔÓÎÌˇ˛ ÔÓËÒÍ
ERROR:app:Exception on /search/ [GET]
Traceback (most recent call last):
  File "C:\Users\ ÓÒÏÓÌ‡‚Ú\Documents\GitHub\lesson12_project_source_v3\main\views.py", line 26, in search_page
    posts = get_posts_by_word(search_query)
NameError: name 'get_posts_by_word' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\! “–≈Õ»Õ√» !\! PYTHON SKYPRO !\lesson12_project_source_v3\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\! “–≈Õ»Õ√» !\! PYTHON SKYPRO !\lesson12_project_source_v3\venv\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\! “–≈Õ»Õ√» !\! PYTHON SKYPRO !\lesson12_project_source_v3\venv\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\! “–≈Õ»Õ√» !\! PYTHON SKYPRO !\lesson12_project_source_v3\venv\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\ ÓÒÏÓÌ‡‚Ú\Documents\GitHub\lesson12_project_source_v3\main\views.py", line 31, in search_page
    except JSONDecoderError:
NameError: name 'JSONDecoderError' is not defined
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 18:46:02] "[35m[1mGET /search/?s=‚‡ HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 18:46:06] "GET /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 18:46:06] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
INFO:root:«‡„ÛÊÂÌÌ˚È Ù‡ÈÎ ÌÂ ËÏÂÂÚ ÙÓÏ‡Ú jpg Ë png
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 18:46:18] "POST /post HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 18:46:21] "GET /post HTTP/1.1" 200 -
ERROR:app:Exception on /post [POST]
Traceback (most recent call last):
  File "E:\! “–≈Õ»Õ√» !\! PYTHON SKYPRO !\lesson12_project_source_v3\venv\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\! “–≈Õ»Õ√» !\! PYTHON SKYPRO !\lesson12_project_source_v3\venv\lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\! “–≈Õ»Õ√» !\! PYTHON SKYPRO !\lesson12_project_source_v3\venv\lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\! “–≈Õ»Õ√» !\! PYTHON SKYPRO !\lesson12_project_source_v3\venv\lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\ ÓÒÏÓÌ‡‚Ú\Documents\GitHub\lesson12_project_source_v3\loader\views.py", line 45, in add_post_page
    post: dict = add_post({'pic': picture_path, 'content': content})
NameError: name 'add_post' is not defined
INFO:werkzeug:127.0.0.1 - - [31/Jul/2022 18:46:49] "[35m[1mPOST /post HTTP/1.1[0m" 500 -
